services:
  backend:
    build: ./back
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  db:
    image: postgres
    restart: always
    volumes:
      - postgresData:/var/lib/postgresql/data
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresData:

networks:
  networksData: