services:
  backend:
    build: ./back
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src
    env_file:
      - ./.env
    command: npx ts-node /app/src/seeding/seed.ts && npx ts-node /app/src/index.ts
    depends_on:
      - db

  frontend:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
