services:
  backend:
    build: ./back
    env_file:
      - ./.env
    volumes:
      - ./back/src:/app/src
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
      - networksData

  frontend:
    build: ./front
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./front/src:/app/src
    ports:
      - 3000:3000
    networks:
      - networksData

  db:
    image: postgres
    restart: always
    volumes:
      - postgresData:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - networksData

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - networksData

volumes:
  postgresData:

networks:
  networksData: