name: jest-ci-wild-carbone

on: pull_request 

jobs:
  test-front:
    runs-on: ubuntu-latest


    steps: 
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto front
        run: cd front && npm i
      - name: Check TS
        run: npx tsc --noEmit
      - name: Check build
        run: npm run build
      - name: run tests
        run: npm test

  test-back:
    runs-on: unbuntu-latest
    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x']
    steps: 
      - name: Check out code 
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Goto back
        run: cd back && npm i
      - name: Check TS
        run: npx tsc --noEmit
      - name: run tests
        run: npm test

  docker:
    needs: test-front
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/Wild-Carbone:Wild-Carbone